### ISSUE TITLE
Braces and Indent

### ISSUE THREAD

**Issue by eduardodgarciac** [trovit/php-code-formatter#2]
Hi, how I can keep the braces in the same line? and how I can use tabs for indentation?

**Comment by poteirard** [comment]
Hi,

I created this repo without the possibility to change the configuration of php_cs_formatter because I didn't need it for my project. You are free to make a pull request with this feature if you want :)

However as the readme in the [bundle](https://github.com/trovit/php-code-formatter-bundle) says you can create your own formatter with the interface Formatter.

Let me know if you need more help :)
